### ISSUE TITLE
オドメトリの軌道が旋回時にワールド座標の原点に沿って半球状に動いてしまう問題

### ISSUE THREAD

**Issue by Hibiki1020** [amslabtech/semantic_mesh_loam#1]

**Comment by ozakiryota** [comment]
整理
* 関数
	* [void LaserOdometry::get_tf_data()](https://github.com/amslabtech/semantic_mesh_loam/blob/f952cfbd3c63bb40264bb0899417e14ba7c45701/src/lib/laserodometry.cpp#L601)
		* 現在のtfを取得
	* [void LaserOdometry::get_relative_trans()](https://github.com/amslabtech/semantic_mesh_loam/blob/f952cfbd3c63bb40264bb0899417e14ba7c45701/src/lib/laserodometry.cpp#L320)
		* t, t-1間のオドメトリの移動量（グローバル）を算出
* 変数
	* odom_data
		* frame_id = /map
	* _last_odom_data
		* frame_id = /map
	* relative_pos_trans
		* 自作クラス？

気づいた点
* 不連続の角度の足し算引き算（[#343-345](https://github.com/amslabtech/semantic_mesh_loam/blob/f952cfbd3c63bb40264bb0899417e14ba7c45701/src/lib/laserodometry.cpp#L343-L345)）
	* diff = atan2(sin(a - b), cos(a - b));
